= Руководство backend-разработчика

== База данных:
. В приложение используется реляционная база данных - https://www.postgresql.org/[PostgreSQL]
. В приложение используется key-value база данных - https://redis.io/[Redis]

=== Подключение к PostgreSQL:
База данных поднимается в контейнере Docker с портом 5432. +
Чтобы подключиться к реляционной БД, необходимо воспользоваться командой из терминала контейнера:
[source, text]
----
psql -U user_name -d db_name
----
Либо использовать любой доступный UI-функционал. (Например: https://dbeaver.io/[DBeaver])

=== Подключение к Redis:
База данных поднимается в контейнере Docker с портом 6379. +
Для подключения к БД можно воспользоваться  https://redis.io/insight/[Redis Insight]

== Запуск приложения
Запуск проекта выполняется средствами Intellij Idea или любой другой удобной IDE. +
Перед запуском проекта необходимо скорректировать .env-файл, указан корректные данные для подключения к системам.

== Генерация SQL-патча для Liquibase
Генерация SQL-патча осуществляется командой
[source, text]
----
gradlew createPatch -Ppatchname="create_user_table" -Ptask="AM-385" -Ptype="DML" -Ppatchversion="01.000.00"
----

=== Проверка приложения
Чтобы выполнить проверку успешного запуска приложения , необходимо вызывать рест: "http://host:port/actuator/health"

Описание аргументов:

. *patchname* - Логическое наименование патча (Например: create_user_table)
. *task* - Номер задачи, в рамках которой создавался скрипт (*Опциональный параметр*)
. *type* - Тип патча (*Опциональный параметр*)
    - *DDL* (SELECT, INSERT, UPDATE, DELETE)
    - *DML* (CREATE, ALTER, DROP)
. *patchversion* - Указание расположения патча (*Опциональный параметр*)

== Блокировка зависимостей
В приложение используется блокировка зависимостей для исключения непредвиденных проблем, связанных с зависимостями (см. подробнее https://docs.gradle.org/current/userguide/dependency_locking.html[docs.gradle] ) +
Блокировка зависимостей осуществляется с помощью gradle task:
[source, text]
----
gradlew resolveAndLockAll --write-locks
----
После добавления или изменения зависимостей необходимо вызвать данную таску.

== Метрики приложения
Сбор метрик приложения осуществляется c помощью Actuator.

== API
При локальном запуске API доступно по ссылке swagger`а: http://localhost:port/swagger-ui/index.html +
Обновление OpenApi возможно через вызов gradle-task "downloadOpenApiSpecification".

=== Работа с API
В приложении используется аутентификация средствами session cookie + CSRF.
Для работы системы необходимо в Docker-е поднять два контейнера: Redis и PostgreSQL.

После успешного запуска приложения необходимо:

. Вызвать endpoint GET /settings/pre-login и из cookie достать значение "XSRF-TOKEN". Выполнить XOR-шифрование.
. Выполнить регистрацию с помощью endpoint POST /authentication/registration, подложив в header "X-XSRF-TOKEN" шифрованное значение, полученное на п.1
. Выполнить аутентификацию с помощью endpoint POST /authentication/login, подложив в header "X-XSRF-TOKEN" шифрованное значение, полученное на п.1
. После успешной аутентификации "XSRF-TOKEN" будет изменен, для дальнейших вызовов endpoint-ов, необходимо будет выполнить XOR-шифрование нового токена и работать с ним.

WARNING: Выполнить XOR-шифрование можно через "XOREncryptedTest"

WARNING: Если вызов со стороны frontend, то XOR-операция токена должна выполняться перед каждым вызовом.

WARNING: OpenApi располагается в /root/openapi/base-project/xxx.yaml

== Соглашения разработки

=== PostgreSQL

[source, text]
----
{suffix}_{tablename}_{columnname(s)}
----

Где suffix равен одному из:

- pkey for a Primary Key constraint;
- key for a Unique constraint;
- excl for an Exclusion constraint;
- idx for any other kind of index;
- fkey for a Foreign key;
- check for a Check constraint;