server:
  port: 8081

spring:
  profiles:
    default: DEV
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true